### ISSUE TITLE
ThirdParty provider post request header 

### ISSUE THREAD

**Issue by renyijiu** [supertokens/supertokens-golang#146]
https://github.com/supertokens/supertokens-golang/blob/7d08329ed4482ee662cb3762108418e74bd0049d/recipe/thirdparty/api/implementation.go#L221

If the provider needs to use other types of content-type (e.g. application/json), it will not be supported. Is there any way to support it? Or am I missing something? thanks.

**Comment by rishabhpoddar** [comment]
@renyijiu we are working on a way where we support this, but for now, you can do it by overriding the whole signinup API and copying the SDK code into your override function and modifying the content-type in there.

**Comment by renyijiu** [comment]
> @renyijiu we are working on a way where we support this, but for now, you can do it by overriding the whole signinup API and copying the SDK code into your override function and modifying the content-type in there.

Thanks for the quick reply, is there a time plan associated with this?

**Comment by rishabhpoddar** [comment]
We now allow overriding of the function which queries the provider.
