### ISSUE TITLE
Improper usage of keyfunc leading to leaking goroutines and compounding scheduled HTTP requests

### ISSUE THREAD

**Issue by MicahParks** [supertokens/supertokens-golang#155]
Currently there are two functions that use the [`github.com/MicahParks/keyfunc`](https://github.com/MicahParks/keyfunc) package.

1. [Apple related function](https://github.com/supertokens/supertokens-golang/blob/master/recipe/thirdparty/providers/apple.go#L170)
2. [Google Workspaces related function](https://github.com/supertokens/supertokens-golang/blob/master/recipe/thirdparty/providers/googleWorkspaces.go#L138)

They both share this snippet of code:
```go
// Create the keyfunc options. Refresh the JWKS every hour and log errors.
refreshInterval := time.Hour
options := keyfunc.Options{
  RefreshInterval: refreshInterval,
}

// Create the JWKS from the resource at the given URL.
jwks, err := keyfunc.Get(jwksURL, options)
if err != nil {
  return claims, err
}

// Parse the JWT.
token, err := jwt.ParseWithClaims(idToken, claims, jwks.Keyfunc)
if err != nil {
  return claims, err
}
```

When using the `RefreshInterval` field in the `keyfunc.Options` data structure, a background goroutine will be launched to refresh the JWKS at the given interval. Additionally, there is a comment that suggests errors from the `keyfunc`'s background goroutine will be logged, however, the `RefreshErrorHandler` field was not specified, so this is not the case. [Reference](https://pkg.go.dev/github.com/MicahParks/keyfunc#Options).

Since the function creates a new `*keyfunc.JWKS` via `keyfunc.Get` every time it is called _and_ it does not end the background goroutine for the `*keyfunc.JWKS`, these two functions leak goroutines every time they are called. This can be problematic because it is a resource leak and each of these leaked goroutines will make an HTTP request to their JWKS endpoints at the given interval, forever.

As a note, a `*keyfunc.JWKS`'s background goroutine can be ended via the [`EndBackground`](https://pkg.go.dev/github.com/MicahParks/keyfunc#JWKS.EndBackground) method or via the context given by the `keyfunc.Options` to the `keyfunc.Get` function.

I suggest doing one of the two things:
1. Pass an empty `keyfunc.Options` to the `keyfunc.Get` function. This will keep the current behavior, but no background goroutine will be launched.
2. Move the creation of the `*keyfunc.JWKS` outside of these functions. (The creation of this data structure is the result of a call to the `keyfunc.Get` function.) This would allow the same `*keyfunc.JWKS` to be reused across function calls. If you chose this option, I would also suggest exposing a way for the users of the `supertokens-golang` package to end any background goroutines.

**Comment by rishabhpoddar** [comment]
Thanks for raising this issue @MicahParks. We will have a loop ASAP.
