### ISSUE TITLE
Does session.GetSessionFromRequestContext support grpc request ?

### ISSUE THREAD

**Issue by renyijiu** [supertokens/supertokens-golang#158]
I have written a simple grpc server to authenticate user requests, but currently the value obtained by "session.GetSessionFromRequestContext" is empty, does it support grpc requests? Or am I using it in the wrong way?

I used postman to request the local grpc service, and the cookie: value was placed in the metadata, and there is information about it in the logs.

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/8318266/180139800-e0e228b1-cede-4e76-b568-7bb1d819d415.png">

The server code:

```go
package grpc

import (
	corev3 "github.com/envoyproxy/go-control-plane/envoy/config/core/v3"
	authv3 "github.com/envoyproxy/go-control-plane/envoy/service/auth/v3"
	typev3 "github.com/envoyproxy/go-control-plane/envoy/type/v3"
	log "github.com/sirupsen/logrus"
	session "github.com/supertokens/supertokens-golang/recipe/session"
	"golang.org/x/net/context"
	"google.golang.org/genproto/googleapis/rpc/status"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/reflection"
	"net"
)

const (
	xUserId         = "x-cos-user-id"
	xOrganizationId = "x-cos-organization-id"
)

type (
	extAuthzServerV3 struct{}
)

type ExtAuthzServer struct {
	grpcServer *grpc.Server
	grpcV3     *extAuthzServerV3
}

func Init() {
	s := NewExtAuthzServer()
	s.startGRPC()
}

func NewExtAuthzServer() *ExtAuthzServer {
	return &ExtAuthzServer{
		grpcV3: &extAuthzServerV3{},
	}
}

func (s *ExtAuthzServer) startGRPC() {
	listener, err := net.Listen("tcp", ":6565")
	if err != nil {
		log.Fatalf("Failed to start gRPC server: %v", err)
		return
	}

	s.grpcServer = grpc.NewServer()

	reflection.Register(s.grpcServer)
	authv3.RegisterAuthorizationServer(s.grpcServer, s.grpcV3)

	log.Printf("Starting gRPC server at %s", listener.Addr())
	if err := s.grpcServer.Serve(listener); err != nil {
		log.Fatalf("Failed to serve gRPC server: %v", err)
		return
	}
}

// Check implements gRPC v3 check request.
func (s *extAuthzServerV3) Check(ctx context.Context, request *authv3.CheckRequest) (*authv3.CheckResponse, error) {
	sessionContainer := session.GetSessionFromRequestContext(ctx)
	log.Infof("sessionContainer is nil: %v", sessionContainer == nil)

	md, ok := metadata.FromIncomingContext(ctx)
	log.Infof("metadata: %v, ok: %v", md, ok)

	log.Infof("request attrs: %v", request.GetAttributes())

	return s.deny(request), nil
}

func (s *extAuthzServerV3) allow(request *authv3.CheckRequest) *authv3.CheckResponse {
	return &authv3.CheckResponse{
		HttpResponse: &authv3.CheckResponse_OkResponse{
			OkResponse: &authv3.OkHttpResponse{
				Headers: []*corev3.HeaderValueOption{
					{
						Header: &corev3.HeaderValue{
							Key:   "x-cos-user-id",
							Value: "hello",
						},
					},
					{
						Header: &corev3.HeaderValue{
							Key:   "x-cos-organization-id",
							Value: request.GetAttributes().String(),
						},
					},
				},
			},
		},
		Status: &status.Status{Code: int32(codes.OK)},
	}
}

func (s *extAuthzServerV3) deny(request *authv3.CheckRequest) *authv3.CheckResponse {
	return &authv3.CheckResponse{
		HttpResponse: &authv3.CheckResponse_DeniedResponse{
			DeniedResponse: &authv3.DeniedHttpResponse{
				Status: &typev3.HttpStatus{Code: typev3.StatusCode_Forbidden},
				Body:   "deny request",
				Headers: []*corev3.HeaderValueOption{
					{
						Header: &corev3.HeaderValue{
							Key:   xUserId,
							Value: "",
						},
					},
					{
						Header: &corev3.HeaderValue{
							Key:   xOrganizationId,
							Value: "",
						},
					},
				},
			},
		},
		Status: &status.Status{Code: int32(codes.PermissionDenied)},
	}
}

```

**Comment by rishabhpoddar** [comment]
The session management of supertokens only supports HTTP and not GRPC. You can enable the JWT feature that we have, and instead of sending the session cookies via GRPC, you can send the JWT and then verify it yourself in your GRPC APIs.

**Comment by renyijiu** [comment]
> The session management of supertokens only supports HTTP and not GRPC. You can enable the JWT feature that we have, and instead of sending the session cookies via GRPC, you can send the JWT and then verify it yourself in your GRPC APIs.

Is there any way to check the accessToken myself? Or parse the accessToken to get out the jwt

**Comment by rishabhpoddar** [comment]
> Or parse the accessToken to get out the jwt

You can do this from the frontend easily. See this: https://supertokens.com/docs/session/common-customizations/sessions/with-jwt/read-jwt#on-the-frontend

And then you can pass that to your API however you like. Keep in mind that you need to enable the jwt feature when you to session.init -> https://supertokens.com/docs/session/common-customizations/sessions/with-jwt/enabling-jwts

**Comment by renyijiu** [comment]
> > Or parse the accessToken to get out the jwt
> 
> You can do this from the frontend easily. See this: https://supertokens.com/docs/session/common-customizations/sessions/with-jwt/read-jwt#on-the-frontend
> 
> And then you can pass that to your API however you like. Keep in mind that you need to enable the jwt feature when you to session.init -> https://supertokens.com/docs/session/common-customizations/sessions/with-jwt/enabling-jwts

I have enabled this configuration, but I just want to ask, is there a func for sdk to check and parse the accessToken by itself? (Because the front end can actually support cookies)

**Comment by rishabhpoddar** [comment]
> is there a func for sdk to check and parse the accessToken by itself

Ah i see. There is no such func directly. There is `GetSession`, but that too reads from the cookies header. But if you open an issue about this separately, we may add such a function.
