### ISSUE TITLE
GoFiber Example: GoFiber ErrorHandler not called

### ISSUE THREAD

**Issue by 8BitJonny** [supertokens/supertokens-golang#194]
# What
Imagine having a normal GoFiber Instance setup like this with a custom [ErrorHandler](https://docs.gofiber.io/api/fiber#config) just to add some custom error formatters. I think thats not a rare case.
```go
app := fiber.New(fiber.Config{
	ErrorHandler: func (ctx *fiber.Ctx, err error) error { return err },
})
```
Then with the current implementation of an auth middleware like its currently shown in the example, the goFiber error handler is never called, because all the response writing already happened in the callback of the `session.verifySession` function on the `net/http` instance of the request

https://github.com/supertokens/supertokens-golang/blob/e716a17d304b1395a17c04fd3af5c7cf402d6612/examples/with-fiber/main.go#L122-L144

(PR incoming to fix this)

**Comment by sattvikc** [comment]
Fixed via - https://github.com/supertokens/supertokens-golang/pull/198
