### ISSUE TITLE
optimalization: redundant loops

### ISSUE THREAD

**Issue by leandergangso** [supertokens/supertokens-golang#220]
I don't see the reason for why two separate loops is needed to extract the values.
Why not have both if checks inside the same first loop?

https://github.com/supertokens/supertokens-golang/blob/bd21fdf4c560066bd6e166edfb844096d33e71ac/recipe/emailpassword/api/implementation.go#L168-L179

ps: this happens in multiple places.

**Comment by rishabhpoddar** [comment]
hey @LeanderGangso you are right. We can have both checks in the same loop. That being said, this is a very tiny optimisation that has little to no effect (IMO). So making this change won't be a priority for us. Please feel free to create a PR for this if you like :)

**Comment by wallstromsimon** [comment]
I need to set up the project, so I can fix this as an intro task. You'll get a PR during the week 👍
