### ISSUE TITLE
not possible to set custom username for smtp

### ISSUE THREAD

**Issue by LeanderGangso** [supertokens/supertokens-golang#221]
Want to use mailtrap which have secrets for both username and password.
So would want the option to set a custom username, instead of using the email as default.

https://github.com/supertokens/supertokens-golang/blob/bd21fdf4c560066bd6e166edfb844096d33e71ac/ingredients/emaildelivery/main.go#L55

I know you can just override, but would be nice to have to option to at a custom username.

**Comment by rishabhpoddar** [comment]
Hey @LeanderGangso we will work on adding this feature. But until then, you can use the custom method of sending an email by overriding the `SendEmail` function. 

Here is an example of how to do this for thirdpartyemailpassword recipe: https://supertokens.com/docs/thirdpartyemailpassword/email-delivery/custom-method

**Comment by rishabhpoddar** [comment]
This feature has been added in golang sdk version >= 0.9.14
