### ISSUE TITLE
Issue with invalidating session upon failed SignInUpPOST  

### ISSUE THREAD

**Issue by jayakrishnan-jayu** [supertokens/supertokens-golang#240]
Steps to reproduce.

override the `originalSignInUpPOST`
[https://supertokens.com/docs/thirdparty/common-customizations/handling-signinup-success#2-on-the-backend](url)

return an error inside the method
```
return tpmodels.SignInUpPOSTResponse{
  OK: nil,
}, fmt.Errorf("Test Error")
```

Doing the above mentioned steps results in the request to `http://localhost:8080/signinup` failing with a status code of 500.
But the session is still being created.

**Comment by sattvikc** [comment]
hello @jayakrishnan-jayu, calling original implementation would have created cookies or headers (based on the mode you are using) to create session. Which results in an active session even though the API returned a 500. If in certain cases, you wish to invalidate the created session, use the following code snippet:

```go
import "github.com/supertokens/supertokens-golang/recipe/session/errors"

// return this in the SignInUpPOST override
return tpmodels.SignInUpPOSTResponse{}, errors.UnauthorizedError{
    ClearTokens: &True,
}
```

**Comment by jayakrishnan-jayu** [comment]
That works, Thank you! ✌🏼
