### ISSUE TITLE
how can i get the avatar and the username ,example i use the github login

### ISSUE THREAD

**Issue by qiuyejianweinuan** [supertokens/supertokens-golang#255]

**Comment by rishabhpoddar** [comment]
See our docs for how to get the access token from the third party provider: https://supertokens.com/docs/thirdparty/common-customizations/getting-provider-access-token (this is for thirdparty recipe, if instead you use thirdpartyemailpassword or thirdpartypasswordless, search in those docs).

Once you have the access token, you can query github to get the info and save it in your db against the user ID, or in the supertokens' user metadata recipe.

**Comment by qiuyejianweinuan** [comment]
> See our docs for how to get the access token from the third party provider: https://supertokens.com/docs/thirdparty/common-customizations/getting-provider-access-token (this is for thirdparty recipe, if instead you use thirdpartyemailpassword or thirdpartypasswordless, search in those docs).
> 
> Once you have the access token, you can query github to get the info and save it in your db against the user ID, or in the supertokens' user metadata recipe.

so, we need to get the user profile by  query github api but not the supertokens api ?

**Comment by rishabhpoddar** [comment]
Yes.
