### ISSUE TITLE
when i use the supertokens, example login with github,i can get the user email and the github id ,but not have the avatar url ,how should i get the avatar url 

### ISSUE THREAD

**Issue by qiuyejianweinuan** [supertokens/supertokens-golang#256]
and i notice  [https://supertokens.com/docs/thirdpartyemailpassword/post-login/getting-provider-access-token] ,and what the difference between the accesstoken on this page  and the method 
`sessionContainer := session.GetSessionFromRequestContext(c.Request.Context())

	if sessionContainer == nil {
		c.JSON(500, "no session found")
		return
	}
	accessToken := sessionContainer.GetAccessToken()`

**Comment by rishabhpoddar** [comment]
The access token returned by `sessionContainer.GetAccessToken()` is the supertokens' access token which is used to query your APIs. This access token is not the same as the github access token.

SuperTokens doesn't yet store the github access token, so you need to save that yourself if you need to.

**Comment by rishabhpoddar** [comment]
Instead of opening issues, for questions, it's best if you join our discord community: https://supertokens.com/discord
