### ISSUE TITLE
question: use of function pointers in recipe interfaces

### ISSUE THREAD

**Issue by urandom** [supertokens/supertokens-golang#271]
Hi,

Why do the recipe interfaces use function pointers for their fields? I'm playing around with them now, and my first thought is that they are quite cumbersome to use. What are the benefits of them being pointers as opposed to just value function types?

**Comment by sattvikc** [comment]
We have done that basically to support overriding of the recipe functions. We do acknowledge that it is not the best way, and better alternatives do exist. Just that we haven't had the bandwidth to make the change.

**Comment by rishabhpoddar** [comment]
Closing this issue for now since this isn't a bug in our SDKs
