### ISSUE TITLE
Issue enforcing required email verification

### ISSUE THREAD

**Issue by gabrielseibel1** [supertokens/supertokens-golang#296]
# Issue enforcing required email verification
Setting up required (not optional) email verification in the backend (Golang) does not protect routes that use session.VerifySession, as the documentation describes. Forcing the verification adding the validator to the middleware works.

## Description
We have a backend (using Gin) that should be email-verification protected on almost every route.

We’ve followed this guide (https://supertokens.com/docs/thirdpartyemailpassword/common-customizations/email-verification/protecting-routes#protecting-backend-api-routes) to try to add it automatically to our (already set-up and working) SuperTokens session validation.

We basically added this piece of code to our recipe in Init:
```go
emailverification.Init(evmodels.TypeInput{
  // This means that VerifySession will now only allow calls if the user has verified their email
  Mode: evmodels.ModeRequired,
}),
```

The guide says, 
> "Routes protected with the verifySession middleware will now additionally check for email verification status."

However, we do not see this happening.

## Steps to Reproduce
1. Create a backend in go, initialize supertokens and set email verification as required
2. Create a route protected by `session.VerifySession`
3. Create a user (no social sign-up) and don't validate the email address
4. Do GET at /auth/user/email/verify , assert email is not verified
5. Try to use the route protected by `session.VerifySession` with the unverified user
6. Observe that route is responding correctly, and it shouldn't

## Partial Solution
When we try this step here (https://supertokens.com/docs/thirdpartyemailpassword/common-customizations/email-verification/protecting-routes#add-email-verification-checks-to-specific-api-routes) , that should be necessary only with evmodels.ModeOptional, the email verification happens correctly!

## Question & Request
Is this a bug on the required email verification mode, or are we just doing something incorrectly?
Right now we can patch this problem by using the “optional” approach, but in the future we would prefer to have it automatically with “required” approach.

**Comment by nkshah2** [comment]
Hi @gabrielseibel1 

Thanks for the detailed issue. So I tried recreating this on my end and it seems to be working fine for me. What SDK version are you using on the frontend and backend?

Heres what I tried:

## Initialising email verification (Same as yours)

```go
emailverification.Init(evmodels.TypeInput{
    Mode: evmodels.ModeRequired,
}),
```

## Using verify session in an API

```go
http.ListenAndServe(":3001", corsMiddleware(
		supertokens.Middleware(http.HandlerFunc(func(rw http.ResponseWriter, r *http.Request) {
			// Handle your APIs..

			if r.URL.Path == "/sessioninfo" {
				session.VerifySession(nil, sessioninfo).ServeHTTP(rw, r)
				return
			}

			rw.WriteHeader(404)
		}))))


func sessioninfo(w http.ResponseWriter, r *http.Request) { ... }
```

and when I call the API with a user who's email has not been verified, the API fails with a 403 which is expected.

----

Can you try recreating the issue with an app built using our CLI? (`npx create-supertokens-app@latest`). Im also including a zip to the project I used, you can try recreating the issue there or use it as a  reference.

[verifysession-ev.zip](https://github.com/supertokens/supertokens-golang/files/11684251/verifysession-ev.zip)

**Comment by nkshah2** [comment]
Closing this since we haven't heard back from you in a while. Feel free to reopen

**Comment by gabrielseibel1** [comment]
Hi, i noticed you're using github.com/supertokens/supertokens-golang v0.12.6, and I'm on v0.10.2 . Will try to update and check it works as your example. I'll reopen if I still face problems, trying to reproduce on a simpler version of my app maybe. Thanks for the help up to this point.

**Comment by gabrielseibel1** [comment]
Yep, updating it worked. Thank you!

**Comment by nkshah2** [comment]
Hi @gabrielseibel1 

Yep passing `nil` will maintain the original behaviour
