### ISSUE TITLE
This causes error when access token is revoked

### ISSUE THREAD

**Issue by ysaakpr** [supertokens/supertokens-golang#298]
https://github.com/supertokens/supertokens-golang/blob/5f5d14836cc9972274caf2588967723906b1cf32/recipe/session/sessionFunctions.go#LL386C3-L386C18

Must be something like this
```
if response["status"].(string) == errors.UnauthorizedErrorStr {
    return nil, fmt.Errorf(errors.UnauthorizedErrorStr)
}
```

**Comment by rishabhpoddar** [comment]
This issue has been fixed in golang SDK version >= 0.12.10
