### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by f-calixto** [supertokens/supertokens-golang#302]
On https://supertokens.com/docs/thirdpartyemailpassword/pre-built-ui/setup/core/with-docker#docker-compose-file, the healthcheck is run under the root user. Please add ['CMD', 'pg_isready', '-U', 'supertokens_user', '-d', 'supertokens'] to specify user and database

**Comment by rishabhpoddar** [comment]
Thanks. We have updated our docs!
