### ISSUE TITLE
405 not allowed only happens in /user/password/reset/token

### ISSUE THREAD

**Issue by irg1008** [supertokens/supertokens-golang#360]
Hi, I only receive CORS error in this endpoint from the frontend. It works on any non-browser client. Also it works with every other single endpoint from the frontend origin. It's just this one.

![image](https://github.com/supertokens/supertokens-golang/assets/47559427/a4aa251d-7c38-4f89-a1d0-7a5d8623c52a)

I know this could be something wrong in my config, but after two days I am not able to find anything.
I tried with the example code in this repo at https://github.com/supertokens/supertokens-golang/blob/master/examples/with-labstack-echo/main.go

Still wouldn't work

Thank you

**Comment by rishabhpoddar** [comment]
What is your CORS config? Also, what are all the response headers from this API call?

**Comment by irg1008** [comment]
I am using the ECHO middleware and then add the CORS headers. Also tried with the example functions and wouldn't work:

```golang
func (s *Server) CORSMiddleware() echo.MiddlewareFunc {
	baseHeaders := []string{echo.HeaderContentType}
	headers := append(baseHeaders, auth.GetHeaders()...)

	return middleware.CORSWithConfig(middleware.CORSConfig{
		AllowOrigins:     []string{s.Config.ClientUrl},
		AllowMethods:     []string{echo.GET, echo.PUT, echo.POST, echo.DELETE, echo.OPTIONS, echo.HEAD, echo.PATCH},
		AllowHeaders:     headers,
		AllowCredentials: true,
	})
}
```

Every call, email verification, log in, signup, everything works except this endpoint.

This are the response headers:
![image](https://github.com/supertokens/supertokens-golang/assets/47559427/5cd5d110-1038-4add-9ccd-5c493ee77d2d)

My first though is that "POST" is not allowed as avalid Method, but then again, why not if it works for the rest of "POST" calls like login or signup. 🤔

**Comment by rishabhpoddar** [comment]
This is out of scope of supertokens, since it seems to be an issue with how CORS is configured / used. Im not sure why the response doesn't have a POST in it even though you have added that to the `AllowMethods` config.

Since this is out of scope for supertokens, i am closing this issue.

**Comment by irg1008** [comment]
You are closing this but this only happens in "/user/password/reset/token" endpoint, not in the rest. ALL the endpoints work as expected except for this very specific one. I don think it must be some kind of problem maybe inside supertokens auth core. I really don't know how to look into it since it's very obscure and the documentation is very plain about it.

Anyway I think this is enough to add to all the things that were deterring me from using supertokens. I will give a little more time to try and understant why this specific endpoint is not working but really I don't see how to resolve this

Thank you.

**Comment by rishabhpoddar** [comment]
A few more questions:
- Is there no call to the OPTIONS API from the frontend for this request?
- What are the request headers for this API call?
