### ISSUE TITLE
jwt parser not accounting for clock skew

### ISSUE THREAD

**Issue by dInquisitor** [supertokens/supertokens-golang#362]
When testing out the supertokens exploratory project, I kept getting a "Token used before issued" error with Google sign in/up.
It turns out that the version of the [golang-jwt](https://pkg.go.dev/github.com/golang-jwt/jwt/v4) package (v4) being used for oauth claims validation does not account for clock skew between my server and IdP server which caused the oauth token to be apparently issued 1 second after it's used [here](https://github.com/supertokens/supertokens-golang/blob/0d35cb9b3c5f4eaef797f15e9cabe2b751000348/recipe/thirdparty/providers/oauth2_impl.go#L130).

The current version (v5) now accounts for clock skew, so is it possible to consider upgrading to the new version?
The only dependency seems to be [keyfunc](http://github.com/MicahParks/keyfunc), which also only needs a version bump as far as I can tell.

**Comment by nkshah2** [comment]
Hi @dInquisitor 

Thanks for the issue! The migration guide for golang-jwt seems pretty extensive so we will need time to evaluate all the changes needed and possible side effects of moving to v5. We will add it to our pipeline and get around to this as soon as we can. Leaving this open so you can keep track of progress on this

**Comment by dInquisitor** [comment]
thank you!

**Comment by rishabhpoddar** [comment]
This has been released in version >= 0.16.0 of the golang SDK.
