### ISSUE TITLE
Supertoken UserInput (Passwordless Authentication)

### ISSUE THREAD

**Issue by jimcru21** [supertokens/supertokens-golang#365]
Im using other SMS Otp Provider

After overriding the default  smsdelivery,
the input.PasswordlessLogin.UserInputCode giver random hex decimal code ( ex: 0x14000546150 ) instead of 6 digit code.

**Comment by nkshah2** [comment]
Hi @jimcru21 

Can you post the code you are using?

**Comment by jimcru21** [comment]
> Are you generating your own OTPs as well?

No.
Im just customize the SMS.
I Dont want to use built in and twillio

**Comment by jimcru21** [comment]
> Hi @jimcru21
> 
> Can you post the code you are using?

Here

`
(*originalImplementation.SendSms) = func(input smsdelivery.SmsType, userContext supertokens.UserContext) error {
		// amount of time the code is alive for (in MS)
		codeLifetime := input.PasswordlessLogin.CodeLifetime
		phoneNumber := input.PasswordlessLogin.PhoneNumber

		// OTP
		userInputCode := input.PasswordlessLogin.UserInputCode
		fmt.Println(codeLifetime)
		fmt.Println(phoneNumber)
		fmt.Println(userInputCode, "user Code")


		return nil

	}
`

**Comment by jimcru21** [comment]
/
/

> Hi @jimcru21
> 
> Can you post the code you are using?


This some Code snippet

`sample`

**Comment by nkshah2** [comment]
Hi @jimcru21 

Unfortunately we cannot recreate the issue, please provide a simple project where you are facing this issue and link it here (either a fresh dummy project or if your current project is open source the github link)

**Comment by nkshah2** [comment]
Hi @jimcru21 `input.PasswordlessLogin.UserInputCode` is a pointer. To get the string value of it you should use `*input.PasswordlessLogin.UserInputCode`

Closing this issue for now, feel free to re-open it if the issue persists
